version: '3'

services:
  telegram-bot:
    build: .
    hostname: telegram-bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_MASTER_HOST=redis-server
      - BOT_RUN_MODE=webhook
      - WEBHOOK_URL
    depends_on:
      - redis-server
    restart: always
  ngrok:
    image: shkoliar/ngrok:latest
    hostname: ngrok
    ports:
      - "4040:4040"
    environment:
      - REGION=eu
      - DOMAIN=telegram-bot
      - PORT=8000
    env_file:
      - .env
    restart: no
  redis-server:
    image: redis/redis-stack-server:latest
    hostname: redis-server
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always