version: '3'

services:
  telegram-bot:
    build: .
    hostname: telegram-telegram_bot
    env_file:
      - .env
    environment:
      - REDIS_MASTER_HOST=redis-server
    depends_on:
      - redis-server
    restart: always
  redis-server:
    image: redis/redis-stack-server:latest
    hostname: redis-server
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always