version: '3.9'

services:
  telegram-bot:
    build: .
    hostname: telegram-bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - BOT_RUN_MODE=webhook
      - REDIS_MASTER_HOST=redis-server
    depends_on:
      - redis-server
    restart: always
  redis-server:
    image: redis/redis-stack-server:latest
    hostname: redis-server
    ports:
      - "6379:6379"
    restart: always
  ngrok:
    image: shkoliar/ngrok:latest
    hostname: ngrok
    ports:
      - "4040:4040"
    env_file:
      - .env
    environment:
      - AUTH_TOKEN=${NGROK_AUTH_TOKEN}
      - REGION=eu
      - DOMAIN=telegram-bot
      - PORT=8000
    restart: no
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource
    restart: unless-stopped
    volumes:
      - ./volumes/grafana-data:/var/lib/grafana

volumes:
  grafana-data:
