version: '3'

services:
  telegram-bot:
    build: .
    hostname: telegram-bot
    env_file:
      - .env
    environment:
      - REDIS_MASTER_HOST=redis
    depends_on:
      - redis
    restart: always
  redis:
    image: redis/redis-stack-server:latest
    hostname: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always