version: '3.9'

services:
  telegram-bot:
    build: .
    hostname: telegram-bot
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - WEBHOOK_URL
      - BOT_RUN_MODE=webhook
      - POSTGRESQL_URL=postgresql://${POSTGRESQL_USERNAME}:${POSTGRESQL_PASSWORD}@pgbouncer:6432/${POSTGRESQL_DATABASE}
      - REDIS_MASTER_HOST=redis
    depends_on:
      - pgbouncer
      - redis
    restart: always
  pgbouncer:
    image: bitnami/pgbouncer:latest
    hostname: pgbouncer
    ports:
      - "6432:6432"
    env_file:
      - ./.env
    environment:
      - POSTGRESQL_HOST=postgres
    volumes:
      - ./deployment/pgbouncer/pgbouncer.ini:/bitnami/pgbouncer/conf/pgbouncer.ini
    restart: always
    depends_on:
      - postgres
  postgres:
    image: bitnami/postgresql:latest
    hostname: postgresql
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - ./deployment/postgresql/conf/override.conf:/opt/bitnami/postgresql/conf/conf.d/override.conf
      - postgres-data:/bitnami/postgresql
    restart: always
  redis:
    image: redis/redis-stack-server:latest
    hostname: redis
    ports:
      - "6379:6379"
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
  ngrok:
    image: shkoliar/ngrok:latest
    hostname: ngrok
    ports:
      - "4040:4040"
    env_file:
      - ./.env
    environment:
      - REGION=eu
      - DOMAIN=telegram-bot
      - PORT=8000
    restart: "no"

volumes:
  postgres-data: