version: '3.9'

services:
  kwork_parser_bot:
    image: coolworldocker/${PROJECT_NAME?}
    build: .
    pull_policy: always
    env_file:
      - .env
    ports:
      - "80:80"
    restart: always
